src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Deliquent</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccountType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Annuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Variable Annuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Variable Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whole Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Incomes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash and Equivalents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ETFs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Brokerage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Management Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdrafts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Term Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Term Loans</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FinServ__OpenDate__c</fullName>
        <label>Date Opened</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__OwnerType__c</fullName>
        <label>Owner Type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FinancialAccountsSelector.cls
/**
 * Encapsulate query logic for Financial Accounts
 */
public class FinancialAccountsSelector extends fflib_SObjectSelector
{
    /**
     * Gets the s object field list.
     * @return     The s object field list.
     */
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            FinServ__FinancialAccount__c.Id,
            FinServ__FinancialAccount__c.Name,
            FinServ__FinancialAccount__c.FinServ__Balance__c,
            FinServ__FinancialAccount__c.FinServ__FinancialAccountType__c,
            FinServ__FinancialAccount__c.FinServ__OwnerType__c,
            FinServ__FinancialAccount__c.FinServ__OpenDate__c,
            FinServ__FinancialAccount__c.FinServ__Status__c
        };
    }

    /**
     * Gets a list of strings representing the fields returned by getSObjectFieldList()
     * @return     The field list string.
     */
    public List<String> getFieldListString()
    {
        List<String> fieldList = new List<String>();
        for(Schema.SObjectField field : getSObjectFieldList()){
            fieldList.add(field.getDescribe().getName());
        }
        return fieldList;
    }

    /**
     * Gets currently represented sobject type name
     * @return     The s object type.
     */
    public Schema.SObjectType getSObjectType()
    {
        return FinServ__FinancialAccount__c.sObjectType;
    }

    /**
     * Default selection of items by id
     * @param      idSet  The identifier set
     * @return     List of financial accounts
     */
    public List<FinServ__FinancialAccount__c> selectById(Set<ID> idSet)
    {
        if (idSet == null || idSet.isEmpty()) return new FinServ__FinancialAccount__c[]{};
        return (List<FinServ__FinancialAccount__c>) selectSObjectsById(idSet);
    }

    public FinServ__FinancialAccount__c[] selectByAccount(Set<Id> accountIds)
    {
        return selectByAccount(accountIds, false);
    }

    /**
     * Select all financial accounts primarily related to a list of accounts
     * @param      accountIds  The account identifiers
     * @return     List of financial accounts
     */
    public FinServ__FinancialAccount__c[] selectByAccount(Set<Id> accountIds, Boolean isCommercial)
    {
        assertIsAccessible();
        String query = String.format(
                'select {0} ' +
                    'from {1} ' +
                    'where FinServ__FinancialAccount__c.FinServ__PrimaryOwner__c in {2} ' +
                    'AND IsCommercial__c =: isCommercial',
                new List<String> {
                    String.join(getFieldListString(), ', '),
                    getSObjectName(),
                    set2soqlInClause(accountIds),
                    String.valueOf(isCommercial)
                }
            );
        System.debug('query: ' + query);
        return (List<FinServ__FinancialAccount__c>) Database.query(query);
    }

    private String set2soqlInClause(Set<Id> idSet)
    {
        if ( idSet == null || idSet.isEmpty() ) return '';
        List<Id> idList = new List<Id>(idSet);
        return '(\'' + String.join(idList, '\',\'') + '\')';
    }
}