src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Exited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsLoan__c</fullName>
        <formula>IF(ISPICKVAL(FinServ__FinancialAccountType__c, &quot;Credit Card&quot;)|| ISPICKVAL(FinServ__FinancialAccountType__c, &quot;Overdrafts&quot;)|| ISPICKVAL(FinServ__FinancialAccountType__c, &quot;Short Term Loans&quot;)|| ISPICKVAL(FinServ__FinancialAccountType__c, &quot;Long Term Loans&quot;), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsLoan</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Represent a movement of money between Financial Accounts</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransactionPatternDetectorTest.cls
@isTest
private class TransactionPatternDetectorTest {

    @testSetup
    private static void generateData() {
        DataGenerator dg = DataGenerator.getInstance();
        dg.createTestEnvironment();
        // now insert some transactions to make a financial account looks like a salary deposit account
        FinServ__FinancialAccount__c[] finAcc = [
            SELECT Id
            FROM FinServ__FinancialAccount__c
            WHERE IsLoan__c = false AND Category__c = 'Retail'
            LIMIT 1];
        System.assert(!finAcc.isEmpty(), 'Data Generation Error!');
        Transaction__c t1 = new Transaction__c(
            Amount__c = 1,
            account_number__c = finAcc[0].Id,
            Status__c = true,
            transaction_date__c = Date.newInstance(2017, System.today().month(), 1),
            transaction_id__c = 'testTransaction1'
        );
        Transaction__c t2 = t1.clone(false, false, false, false);
        t2.transaction_date__c = Date.newInstance(2017, System.today().month() - 1, 1);
        t2.transaction_id__c = 'testTransaction2';
        Transaction__c t3 = t1.clone(false, false, false, false);
        t3.transaction_date__c = Date.newInstance(2017, System.today().month() - 2, 1);
        t3.transaction_id__c = 'testTransaction3';
        insert new Transaction__c[]{t1, t2, t3};
    }

    @isTest
    private static void testSalaryDetection() {
        Test.startTest();
            // given
            TransactionPatternDetector tpd = new TransactionPatternDetector();
            // when
            database.executebatch(tpd, 200);
        Test.stopTest();
        // then
        Account[] accountsWithSalary = [SELECT Id FROM Account WHERE Salary__c != null];
        System.assert(accountsWithSalary.size() >= 1, 'Transaction pattern detection failed!');
    }

}