src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CommercialBalance__c</fullName>
        <label>Commercial Deposit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CommercialLoan__c</fullName>
        <label>Commercial Loans</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccountRole__c.object
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <formula>FinServ__FinancialAccount__r.FinServ__Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the organizational entity that is involved with the financial account.</description>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Roles</relationshipLabel>
        <relationshipName>FinancialAccountRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinancialAccountCategory__c</fullName>
        <formula>TEXT(FinServ__FinancialAccount__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Financial Account Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsLinkingPrimaryOwner__c</fullName>
        <description>Return TRUE if the role is linking a financial account to its primary owner</description>
        <formula>IF(
					FinServ__FinancialAccount__r.FinServ__PrimaryOwner__c =   FinServ__RelatedAccount__c , TRUE, FALSE )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsLinkingPrimaryOwner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLoan__c</fullName>
        <formula>FinServ__FinancialAccount__r.IsLoan__c</formula>
        <label>IsLoan</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FinancialAccountRoles.cls
/**
 * See https://github.com/financialforcedev/fflib-apex-common for more info
 *
 * Install library via
 *   https://githubsfdeploy.herokuapp.com/app/githubdeploy/financialforcedev/fflib-apex-common
 */

/**
 * Encapsulates all behaviour logic relating to the FinServ__FinancialAccountRole__c object
 *
 * For more guidelines and details see
 *   https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Domain_Layer
 *
 **/
public class FinancialAccountRoles extends fflib_SObjectDomain
{
    private FinServ__FinancialAccountRole__c[] filteredRecords;
    private Map<Id, Account> accountsMap = new Map<Id, Account>();
    private Map<Id, Account> oldAccountsMap = new Map<Id, Account>();


    public FinancialAccountRoles(List<FinServ__FinancialAccountRole__c> records)
    {
        super(records);
        this.filteredRecords = new FinServ__FinancialAccountRole__c[]{};
    }

    public override void onValidate()
    {
        for(FinServ__FinancialAccountRole__c record : (List<FinServ__FinancialAccountRole__c>) Records)
        {
            // no need to check for the financial account since it is a master detail
            if (record.Finserv__RelatedAccount__c != null && !record.IslinkingPrimaryOwner__c) {
                filteredRecords.add(record);
            }
        }
    }

    public override void onValidate(Map<Id,SObject> existingRecords)
    {
        for(FinServ__FinancialAccountRole__c record : (List<FinServ__FinancialAccountRole__c>) Records)
        {
            // no need to check for the financial account since it is a master detail
            if (record.Finserv__RelatedAccount__c != null && !record.IslinkingPrimaryOwner__c) {
                filteredRecords.add(record);
            }
        }
    }

    public override void onAfterInsert()
    {

    }

    private Map<Id, Account> getAccountsMap()
    {
        return this.getAccountsMap(null);
    }

    private Map<Id, Account> getAccountsMap(FinServ__FinancialAccountRole__c[] loopRecords)
    {
        Set<Id> accounts = new Set<Id>();
        if (loopRecords == null || loopRecords.isEmpty()) {
            loopRecords = Records;
        } else {
            loopRecords.addAll((FinServ__FinancialAccountRole__c[]) Records);
        }
        for(FinServ__FinancialAccountRole__c fa: loopRecords) {
            accounts.add(fa.Finserv__RelatedAccount__c);
        }
        Map<Id, Account> accountsMap = new Map<Id, Account>(
            [SELECT CommercialBalance__c, CommercialLoan__c
                FROM Account
                WHERE Id IN: accounts FOR UPDATE]
        );
        return accountsMap;
    }

    private void rollUp(FinServ__FinancialAccountRole__c[] roles, Boolean subtract)
    {
        for(FinServ__FinancialAccountRole__c far: roles) {
            Account accToUpdate = accountsMap.get(far.Finserv__RelatedAccount__c);
            if (String.isBlank(far.FinancialAccountCategory__c)) continue;
            String suffix = far.IsLoan__c && far.FinancialAccountCategory__c != 'Wealth' ? 'Loan__c' : 'Balance__c';
            Decimal sum = (Decimal) accToUpdate.get(far.FinancialAccountCategory__c + suffix);
            if (sum == null) sum = 0;
            if (!subtract) sum += far.Balance__c != null ? far.Balance__c : 0.0;
            else           sum -= far.Balance__c != null ? far.Balance__c : 0.0;
            accToUpdate.put(far.FinancialAccountCategory__c + suffix, sum);
        }
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable2
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new FinancialAccountRoles(sObjectList);
        }

        public fflib_SObjectDomain construct(List<SObject> sObjectList, SObjectType sObjectType)
        {
            return new FinancialAccountRoles(sObjectList);
        }
    }
}