src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__FinancialAccountNumber__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Represent a movement of money between Financial Accounts</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransactionRest.cls
/**
 * Example call for transaction creation:
 * {
 *  "request": {
 *      "giving": "bca1",
 *      "receiving": "slda1",
 *      "amount": 12311.2
 *  }
 * }
 */
@RestResource(urlMapping='/transactionApi')
global with sharing class TransactionRest  {

    global class Response {
        global Boolean outcome;
        global String[] messages;
        global String[] errors;
        global Id itemId;
        global Response() {
            this.outcome = false;
            this.messages = new String[]{};
            this.errors = new String[]{};
        }
    }

    @HttpGet
    global static Transaction__c show() {
        Transaction__c obj;
        return obj;
    }

    @HttpPost
    global static Response create(Map<String, String> request) {
        FinServ__FinancialAccount__c receiver = new FinServ__FinancialAccount__c(
            FinServ__FinancialAccountNumber__c = request.get('account_number')
        );
        Transaction__c newTransaction = new Transaction__c(
            Amount__c = Decimal.valueOf(request.get('amount')),
            Account_number__r = receiver
        );
        request.remove('amount');
        request.remove('account_number');

        for (String key : request.keySet()) {
            newTransaction.put(key + '__c', request.get(key));
        }

        Response resp = new Response();
        try {
            insert newTransaction;
        } catch (DmlException dmle) {
            resp.outcome = false;
            resp.errors.add('Cannot create transaction.');
            resp.errors.add(dmle.getMessage());
            return resp;
        }
        resp.outcome = true;
        resp.itemId = newTransaction.Id;
        resp.messages.add('Operation successful');
        return resp;
    }

    @HttpPut
    global static Transaction__c updateObject() {
        Transaction__c obj;
        return obj;
    }

    @HttpDelete
    global static void remove() {}

}