src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccountRole__c.object
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <description>Financial account that this role is related to.</description>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Roles</relationshipLabel>
        <relationshipName>FinancialAccountRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FinancialAccountRolesSelectorTest.cls
@isTest
private class FinancialAccountRolesSelectorTest {

    @testSetup
    private static void generateData() {
        DataGenerator dg = DataGenerator.getInstance();
        dg.createTestEnvironment();
    }

    @isTest
    private static void testInterface() {
        Test.startTest();
            // given
            FinancialAccountRolesSelector fars = new FinancialAccountRolesSelector();
            // when
            List<Schema.SObjectField> fieldList = fars.getSObjectFieldList();
            Schema.SObjectType accType = fars.getSObjectType();
            Map<Id, FinServ__FinancialAccountRole__c> accIds = new Map<Id, FinServ__FinancialAccountRole__c>(
                [SELECT Id FROM FinServ__FinancialAccountRole__c LIMIT 50000]
            );
            FinServ__FinancialAccountRole__c[] accs = fars.selectById(accIds.keySet());
        Test.stopTest();
        // then
        System.assert(!fieldList.isEmpty(), 'No fields provided to fflib interface.');
        System.assertEquals(accType, FinServ__FinancialAccountRole__c.SObjectType);
        System.assertEquals(accIds.size(), accs.size(), 'Query mismatch.');
    }

    @isTest
    private static void testSelection() {
        // given
        FinServ__FinancialAccountRole__c[] ctrlFinAcc = [SELECT Id, Name
            FROM FinServ__FinancialAccountRole__c
            WHERE FinServ__FinancialAccount__r.Category__c = 'Retail'
            LIMIT 50000];
        Map<Id, Account> ctrlAccount = new Map<Id, Account>([SELECT Id FROM Account LIMIT 50000]);
        System.assert(!ctrlFinAcc.isEmpty() && !ctrlAccount.isEmpty(), 'Data configuration error.');
        Test.startTest();
            FinancialAccountRolesSelector fars = new FinancialAccountRolesSelector();
            // when
            FinServ__FinancialAccountRole__c[] roles = fars.selectByAccount(ctrlAccount.keySet());
        Test.stopTest();
        // then
        System.assertEquals(roles.size(), ctrlFinAcc.size(), 'Query Mismatch.');
    }

    @isTest
    private static void testDefaultRecordType() {
        // given
        Id ctrlId = [SELECT Id
            FROM RecordType
            WHERE SObjectType = 'FinServ__FinancialAccountRole__c' AND DeveloperName = 'AccountRole'].Id;
        Test.startTest();
            // when
            Id rtId = FinancialAccountRolesSelector.getDefaultRecordType();
        Test.stopTest();
        // then
        System.assertEquals(ctrlId, rtId, 'Query Mismatch.');
    }
}