src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FinancialAccountsSelectorTest.cls
@isTest
private class FinancialAccountsSelectorTest {

    @testSetup
    public static void testDataSetup()
    {
        // Get record types
        RecordType individualAccount = [SELECT Id FROM RecordType
            WHERE SObjectType = 'Account' AND DeveloperName = 'IndustriesIndividual'];

        // Insert test accounts
        Account[] testAccounts = new Account[]{
            new Account(Name = 'testAccount1', RecordTypeId = individualAccount.Id),
            new Account(Name = 'testAccount2', RecordTypeId = individualAccount.Id),
            new Account(Name = 'testAccount3', RecordTypeId = individualAccount.Id)
        };
        insert testAccounts;

        // Insert test financial accounts + roles
        FinServ__FinancialAccount__c[] testFinAccounts = new FinServ__FinancialAccount__c[]{
            new FinServ__FinancialAccount__c(Name = 'testFinAccount1',
                FinServ__PrimaryOwner__c = testAccounts[0].Id,
                Category__c = 'Retail')
        };
        insert testFinAccounts;
    }

	@isTest
    static void testDML() {
        FinServ__FinancialAccount__c tempFinAcc = [SELECT Id, FinServ__PrimaryOwner__c FROM FinServ__FinancialAccount__c][0];
        Account tempOwner = [SELECT Id FROM Account WHERE Name = 'testAccount1'];
		System.assertEquals(tempFinAcc.FinServ__PrimaryOwner__c, tempOwner.Id);
	}

}