src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FinancialAccounts.cls
/**
 * See https://github.com/financialforcedev/fflib-apex-common for more info
 *
 * Install library via
 *   https://githubsfdeploy.herokuapp.com/app/githubdeploy/financialforcedev/fflib-apex-common
 */

/**
 * Encapsulates all behaviour logic relating to the FinServ__FinancialAccount__c object
 *
 * For more guidelines and details see
 *   https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Domain_Layer
 *
 **/
public class FinancialAccounts extends fflib_SObjectDomain
{

    private List<FinServ__FinancialAccount__c> sumRecords = new List<FinServ__FinancialAccount__c>();
    private List<FinServ__FinancialAccount__c> oldSumRecords = new List<FinServ__FinancialAccount__c>();

    public FinancialAccounts(List<FinServ__FinancialAccount__c> records)
    {
        super(records);
    }

    public override void onValidate()
    {
        sumRecords = [SELECT Category__c, FinServ__Balance__c, FinServ__PrimaryOwner__r.Retail_Financial_Accounts__c,
                FinServ__PrimaryOwner__r.Wealth_AUM__c, FinServ__PrimaryOwner__r.Commercial_Financial_Accounts__c
            FROM FinServ__FinancialAccount__c
            WHERE Id IN: System.Trigger.newMap.keySet()];
        if (!System.Trigger.isInsert) {
            oldSumRecords = [SELECT Category__c, FinServ__Balance__c, FinServ__PrimaryOwner__r.Retail_Financial_Accounts__c,
                    FinServ__PrimaryOwner__r.Wealth_AUM__c, FinServ__PrimaryOwner__r.Commercial_Financial_Accounts__c
                FROM FinServ__FinancialAccount__c
                WHERE Id IN: System.Trigger.oldMap.keySet()];
        }
    }

    public override void onValidate(Map<Id,SObject> existingRecords)
    {
        for(FinServ__FinancialAccount__c record : (List<FinServ__FinancialAccount__c>) Records)
        {
        }
    }

    public override void onAfterInsert()
    {
        List<Account> primaryOwners = new List<Account>();
        for(FinServ__FinancialAccount__c record : sumRecords)
        {
            Account toAdd = new Account(Id = record.FinServ__PrimaryOwner__c);
            if(record.FinServ__Balance__c == null) {
                record.FinServ__Balance__c = 0;
            }
            if (record.Category__c == 'Retail') {
                toAdd.Retail_Financial_Accounts__c = record.FinServ__PrimaryOwner__r.Retail_Financial_Accounts__c + record.FinServ__Balance__c;
            }
            if (record.Category__c == 'Wealth') {
                toAdd.Wealth_AUM__c = record.FinServ__PrimaryOwner__r.Wealth_AUM__c + record.FinServ__Balance__c;
            }
            if (record.Category__c == 'Commercial') {
                toAdd.Commercial_Financial_Accounts__c = record.FinServ__PrimaryOwner__r.Commercial_Financial_Accounts__c + record.FinServ__Balance__c;
            }
            primaryOwners.add(toAdd);
        }
        update primaryOwners;
    }

    public override void onAfterUpdate(Map<Id,SObject> existingRecords)
    {
        List<Account> primaryOwners = new List<Account>();
        for(FinServ__FinancialAccount__c record : oldSumRecords)
        {
            Account toAdd = new Account(Id = ((FinServ__FinancialAccount__c) existingRecords.get(record.Id)).FinServ__PrimaryOwner__c);
            if(record.FinServ__Balance__c == null) {
                record.FinServ__Balance__c = 0;
            }
            if (record.Category__c == 'Retail') {
                toAdd.Retail_Financial_Accounts__c = record.FinServ__PrimaryOwner__r.Retail_Financial_Accounts__c - record.FinServ__Balance__c;
            }
            if (record.Category__c == 'Wealth') {
                toAdd.Wealth_AUM__c = record.FinServ__PrimaryOwner__r.Wealth_AUM__c - record.FinServ__Balance__c;
            }
            if (record.Category__c == 'Commercial') {
                toAdd.Commercial_Financial_Accounts__c = record.FinServ__PrimaryOwner__r.Commercial_Financial_Accounts__c - record.FinServ__Balance__c;
            }
            primaryOwners.add(toAdd);
        }
        update primaryOwners;
        primaryOwners.clear();

        for(FinServ__FinancialAccount__c record : sumRecords)
        {
            Account toAdd = new Account(Id = record.FinServ__PrimaryOwner__c);
            if(record.FinServ__Balance__c == null) {
                record.FinServ__Balance__c = 0;
            }
            if (record.Category__c == 'Retail') {
                toAdd.Retail_Financial_Accounts__c = record.FinServ__PrimaryOwner__r.Retail_Financial_Accounts__c + record.FinServ__Balance__c;
            }
            if (record.Category__c == 'Wealth') {
                toAdd.Wealth_AUM__c = record.FinServ__PrimaryOwner__r.Wealth_AUM__c + record.FinServ__Balance__c;
            }
            if (record.Category__c == 'Commercial') {
                toAdd.Commercial_Financial_Accounts__c = record.FinServ__PrimaryOwner__r.Commercial_Financial_Accounts__c + record.FinServ__Balance__c;
            }
            primaryOwners.add(toAdd);
        }
        update primaryOwners;
    }

    public override void onAfterDelete()
    {
        List<Account> primaryOwners = new List<Account>();
        for(FinServ__FinancialAccount__c record : sumRecords)
        {
            Account toAdd = new Account(Id = record.FinServ__PrimaryOwner__c);
            if(record.FinServ__Balance__c == null) {
                record.FinServ__Balance__c = 0;
            }
            if (record.Category__c == 'Retail') {
                toAdd.Retail_Financial_Accounts__c = record.FinServ__PrimaryOwner__r.Retail_Financial_Accounts__c - record.FinServ__Balance__c;
            }
            if (record.Category__c == 'Wealth') {
                toAdd.Wealth_AUM__c = record.FinServ__PrimaryOwner__r.Wealth_AUM__c - record.FinServ__Balance__c;
            }
            if (record.Category__c == 'Commercial') {
                toAdd.Commercial_Financial_Accounts__c = record.FinServ__PrimaryOwner__r.Commercial_Financial_Accounts__c - record.FinServ__Balance__c;
            }
            primaryOwners.add(toAdd);
        }
        update primaryOwners;
    }

    public void someMethod()
    {
        for(FinServ__FinancialAccount__c record : (List<FinServ__FinancialAccount__c>) Records)
        {
        }
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable2
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new FinancialAccounts(sObjectList);
        }

        public fflib_SObjectDomain construct(List<SObject> sObjectList, SObjectType sObjectType)
        {
            return new FinancialAccounts(sObjectList);
        }
    }
}